export enum Symbols {
  'equivales' = '\u2261 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;eq',
  'notEquivales' = '\u2262 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;nev',
  'implies' = '\u21d2 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;im',
  'not' = '\u00AC &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;not',
  'conjunction' = '\u22c0 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;an',
  'disjunction' = '\u22c1 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;or',
  'emptySet' = '\u2205 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;es',
  'union' = '\u222A &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;un',
  'intersection' = '\u2229 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;in',
  'powerSet' = '<i>P</i> &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;ps',
  'gets' = '\u2254 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;ts',
  'genericQuantifier' = '\u2605 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;st',
  'atLeast' = '\u2264 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;ge',
  'atMost' = '\u2265 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;le',
  'elementOf' = '\u2208 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;el',
  'notElementOf' = '\u2209 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;nel',
  'properSuperset' = '\u2283 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;pp',
  'superset' = '\u2287 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;sp',
  'notProperSubset' = '\u2284 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;npb',
  'notSubset' = '\u2288 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;nsb',
  'notProperSuperset' = '\u2285 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;npp',
  'notSuperset' = '\u2289 &nbsp; &nbsp; &nbsp; &nbsp; &thinsp; &thinsp; ;nsp'
}
